### ISSUE TITLE
QUESTION: debug extension in browser

### ISSUE THREAD

**Issue by mxwiz** [tshaddix/react-chrome-redux-examples#9]
Guys, how can I debug extension in browser? I would like to have access to source code from chrome console, is it possible?

**Comment by MarcBouchard** [comment]
@mxwiz Yes, this solution might come a bit late but here's how you can access each page:

### Popup page (popup.js)
Right click on the extension badge and select "Inspect Popup" from the context menu.

### Background page (event.js)
The background source code is accessed directly through the extensions page where you load/refresh your chrome extension in the "Inspect views" section.

### Content page (content.js)
The content scripts source code is found by directly inspecting the page source code, clicking on the "Sources" tab and in the window that appears selecting "Content scripts". The "Sources" tab is selected by default here.

**Note:** You might have to reload the extension page with these debugging windows open for the .js files to appear. Chrome doesn't seem to pickup on all the source files sometimes, not sure what causes this bug. Also, the JS in these files will look strange since the ES6 syntax has been transpiled with babel and webpack but it should still be intuitive enough for debugging.

Hope this helps.

**Comment by tshaddix** [comment]
Closing for now. Thanks @MarcBouchard !
